#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : connman-gtk
Version  : 1.1.1
Release  : 9
URL      : https://github.com/jgke/connman-gtk/archive/v1.1.1.tar.gz
Source0  : https://github.com/jgke/connman-gtk/archive/v1.1.1.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
Requires: connman-gtk-bin = %{version}-%{release}
Requires: connman-gtk-data = %{version}-%{release}
Requires: connman-gtk-license = %{version}-%{release}
Requires: connman-gtk-locales = %{version}-%{release}
Requires: connman-gtk-man = %{version}-%{release}
BuildRequires : gettext
BuildRequires : intltool
BuildRequires : intltool-dev
BuildRequires : perl(XML::Parser)
BuildRequires : pkgconfig(glib-2.0)
BuildRequires : pkgconfig(gtk+-3.0)
BuildRequires : pkgconfig(openconnect)
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
connman-gtk
===========
GTK GUI for ConnMan.
![screenshot-1](https://raw.githubusercontent.com/jgke/jgke.github.io/connman-gtk/connman-gtk-1.png)
![screenshot-2](https://raw.githubusercontent.com/jgke/jgke.github.io/connman-gtk/connman-gtk-2.png)

%package bin
Summary: bin components for the connman-gtk package.
Group: Binaries
Requires: connman-gtk-data = %{version}-%{release}
Requires: connman-gtk-license = %{version}-%{release}

%description bin
bin components for the connman-gtk package.


%package data
Summary: data components for the connman-gtk package.
Group: Data

%description data
data components for the connman-gtk package.


%package license
Summary: license components for the connman-gtk package.
Group: Default

%description license
license components for the connman-gtk package.


%package locales
Summary: locales components for the connman-gtk package.
Group: Default

%description locales
locales components for the connman-gtk package.


%package man
Summary: man components for the connman-gtk package.
Group: Default

%description man
man components for the connman-gtk package.


%prep
%setup -q -n connman-gtk-1.1.1
cd %{_builddir}/connman-gtk-1.1.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1589411131
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%autogen --disable-static --enable-status-icon=yes
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1589411131
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/connman-gtk
cp %{_builddir}/connman-gtk-1.1.1/COPYING %{buildroot}/usr/share/package-licenses/connman-gtk/4cc77b90af91e615a64ae04893fdffa7939db84c
%make_install
%find_lang connman-gtk

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/connman-gtk

%files data
%defattr(-,root,root,-)
/usr/share/applications/connman-gtk.desktop
/usr/share/glib-2.0/schemas/net.connman.gtk.gschema.xml

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/connman-gtk/4cc77b90af91e615a64ae04893fdffa7939db84c

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/connman-gtk.1

%files locales -f connman-gtk.lang
%defattr(-,root,root,-)

