#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : connman-gtk
Version  : 1.1.1
Release  : 5
URL      : https://github.com/jgke/connman-gtk/archive/v1.1.1.tar.gz
Source0  : https://github.com/jgke/connman-gtk/archive/v1.1.1.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
Requires: connman-gtk-bin
Requires: connman-gtk-data
Requires: connman-gtk-locales
Requires: connman-gtk-doc
BuildRequires : gettext
BuildRequires : intltool
BuildRequires : intltool-dev
BuildRequires : perl(XML::Parser)
BuildRequires : pkgconfig(glib-2.0)
BuildRequires : pkgconfig(gtk+-3.0)
BuildRequires : pkgconfig(openconnect)
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
connman-gtk
===========
GTK GUI for ConnMan.
![screenshot-1](https://raw.githubusercontent.com/jgke/jgke.github.io/connman-gtk/connman-gtk-1.png)
![screenshot-2](https://raw.githubusercontent.com/jgke/jgke.github.io/connman-gtk/connman-gtk-2.png)

%package bin
Summary: bin components for the connman-gtk package.
Group: Binaries
Requires: connman-gtk-data

%description bin
bin components for the connman-gtk package.


%package data
Summary: data components for the connman-gtk package.
Group: Data

%description data
data components for the connman-gtk package.


%package doc
Summary: doc components for the connman-gtk package.
Group: Documentation

%description doc
doc components for the connman-gtk package.


%package locales
Summary: locales components for the connman-gtk package.
Group: Default

%description locales
locales components for the connman-gtk package.


%prep
%setup -q -n connman-gtk-1.1.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1498577213
%autogen --disable-static --enable-status-icon=yes
make V=1  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1498577213
rm -rf %{buildroot}
%make_install
%find_lang connman-gtk

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/connman-gtk

%files data
%defattr(-,root,root,-)
/usr/share/applications/connman-gtk.desktop
/usr/share/glib-2.0/schemas/net.connman.gtk.gschema.xml

%files doc
%defattr(-,root,root,-)
%doc /usr/share/man/man1/*

%files locales -f connman-gtk.lang
%defattr(-,root,root,-)

